config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :cart_items
  devise_for :users
  resources :foods, :shops, :carts
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :food
  belongs_to :cart

  def total_price
  	self.count * self.price
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :shop

	has_attached_file :image,
                     styles: { medium: '300x300>', thumb: '100x100>'},
                     default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                     content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :foods
	has_many :carts

	has_attached_file :image,
                       styles: { medium: '300x300>', thumb: '100x100>'},
                       default_url: '/images/:style/missing.png'
    validates_attachment_content_type :image, 
                       content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/user.rb
class User < ApplicationRecord
	has_many :carts
	has_many :shops
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def total_order_price
  		@result = 0
  		self.carts.each do |cart| 
  		cart.cart_items.each do |cart_item| 
  			@result = @result + (cart_item.price * cart_item.count)
  		end
  	end
  	@result
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.find_by_food_id_and_cart_id(params[:cart_item][:food_id], params[:cart_item][:cart_id])
    
    unless @cart_item 
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.save
      redirect_to :back
    else
      # @cart_item.update_attribute(count, params[:cart_item][:count])
      @cart_item.count += params[:cart_item][:count].to_i
      @cart_item.save
      redirect_to :back
    end



    # respond_to do |format|
    #   if @cart_item.save
    #   else
    #     format.html { render :new }
    #     format.json { render json: @cart_item.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to :back, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:name, :count, :price, :food_id, :cart_id)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @cart = Cart.new
  end

  
  def index
    @carts = current_user.carts

    @carts.each do |cart|
      cart.destroy
    end

    redirect_to :back
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

	def index
		@shops = Shop.all
	end

	def show
		@shop = Shop.find(params[:id])
		@foods = @shop.foods
		@carts = @shop.carts
		if user_signed_in?
		@cart = current_user.carts.where(shop_id: @shop).first_or_create
		end
		# if current_user
		# 	@cart = Cart.find_by_user_id_and_shop_id(current_user.id, @shop.id).first_of_create
		# end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(cart_item) do |f| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :count %>
    <%= f.number_field :count %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :food_id %>
    <%= f.text_field :food_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>Price</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.name %></td>
        <td><%= cart_item.count %></td>
        <td><%= cart_item.price %></td>
        <td><%= cart_item.food %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cart_item.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @cart_item.count %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart_item.price %>
</p>

<p>
  <strong>Food:</strong>
  <%= @cart_item.food %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labarotorka43</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Admin', admin_dashboard_path %></li>
        <% end %>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><a href="#">View orders</a></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<br>
<br>
<br>

			<div>
				<%= yield %>
			</div>
  </body>
</html>

app/views/shops/index.html.erb
<div class="row">
	<% @shops.each do |shop| %>
	<div class="col-md-4 cafe-preview">
	<p align="center"><%= image_tag shop.image.url(:medium) %></p>
		<strong>
			<p align="center">
				<%= link_to shop.name, shop_path(shop) %>
			</p>
		</strong>
	</div>
	<% end %>
</div>

app/views/shops/show.html.erb
<h1 align="center"><%= @shop.description %></h1>
<br>
<div class="row">
		<% @foods.each do |food| %>
	<div class="col-md-4">
			<strong>
				<p align="center"><%= image_tag food.image.url(:medium) %></p>
				<p align="center"><%= food.name %></p>
				<p align="center"><%= food.description %></p>
				<p align="center"><%= food.price %></p>
			</strong>
			<% if user_signed_in? %>
				<%= form_for CartItem.new do |f| %>
				      <%= f.hidden_field :food_id, value: food.id %>
      				  <%= f.hidden_field :cart_id, value: @cart.id %>
      				  <%= f.hidden_field :price, value: food.price %>
      				  <%= f.hidden_field :name, value: food.name %>
      				  <%= f.number_field :count, value: 1 %>
				<%= f.submit 'Заказать', class: "btn btn-danger product#{food.id}" %>
			<% end %>
			<% end %>

	</div>
		<% end %>
		<% if current_user %>
			
        <div id="cartStyle" class="col-sm-3">
				<h3 align="center">Carts from: <%= current_user.name %></h3>
				<table class="table">
					<tr id="textStyle">
						<th>Name</th>
						<th>Quantity</th>
						<th>Summ</th>
						<th>Delete</th>
					</tr>

					<% current_user.carts.each do |cart| %>
						<% cart.cart_items.each do |item| %>
						<tr id="textStyle2" align="center" >
							<td valign="baseline"><%= item.name %></td>
							<td><%= item.count %></td>
							<td><%= item.total_price %> Сом</td>
							<td><%= link_to "", cart_item_path(item), method: :delete,  class: 'glyphicon glyphicon-floppy-remove' %></td>
						</tr>
						<% end %>
					<% end %>
				</table>
				<strong id="textStyle">
				TOTAL PRICE FROM CART: <%= current_user.total_order_price %> Сом
				</strong>
				<div style="margin:10px; padding:0px;">
					<%= link_to 'Оформить заказ',  carts_path, class: 'btn btn-primary' %>
				</div>
				<div style="margin:10px; padding:0px;">
					<%= link_to 'Очистить корзину',  carts_path, class: 'btn btn-danger' %>
				</div>
			</div>
		<% end %>